name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v3
    
    - name: Create Composer directory
      run: mkdir $GITHUB_WORKSPACE/.composer
    
    - uses: actions/cache@v3
      with:
        path: $GITHUB_WORKSPACE/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/install.sh') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Add HTTP basic auth credentials
      run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/.composer/auth.json

    - name: Install Magento2
      run: ./build.sh
      
    - name: Remove auth.json file
      run: rm -f $GITHUB_WORKSPACE/.composer/auth.json

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: phoenixmedia/magento2:${{ steps.extract_branch.outputs.branch }}
